version: "2"
services:
  template-service:
    image: template-service
    links:
      - db
      - log
    ports:
      - "8080:8080"
  db:
    image: openlmis/postgres
    ports:
      - "5432"
  log:
    image: openlmis/rsyslog
    volumes:
      - '../logs/template-service:/var/log'
